### ISSUE TITLE
1. 프로젝트 구조 설계

### ISSUE THREAD

**Issue by SeongjinDaniel** [f-lab-edu/video-hosting-service#1]
프로젝트를 시작합니다

**Comment by f-lab-dev** [comment]
`good first issue` 라벨이 어떤걸 의미하는지 알아보시고 달면 좋을 것 같네요~

**Comment by f-lab-dev** [comment]
그리고 프로젝트 시작이라기보다는 프로젝트 구조 설계 등으로 잡는게 더 프로페셔널해 보일 것 같고요

**Comment by f-lab-dev** [comment]
PR이 머지되었으면 이 이슈는 close 해주시고 회원가입 구현 들어가시면 될 것 같습니다
